// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dictionary.sql

package database

import (
	"context"
)

const getKanji = `-- name: GetKanji :one
SELECT kanji, onyomi, kunyomi, imi, itaiji, bushu FROM dictionary WHERE kanji = $1
`

func (q *Queries) GetKanji(ctx context.Context, kanji string) (Dictionary, error) {
	row := q.db.QueryRowContext(ctx, getKanji, kanji)
	var i Dictionary
	err := row.Scan(
		&i.Kanji,
		&i.Onyomi,
		&i.Kunyomi,
		&i.Imi,
		&i.Itaiji,
		&i.Bushu,
	)
	return i, err
}
