// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Dictionary struct {
	Kanji   string
	Onyomi  sql.NullString
	Kunyomi sql.NullString
	Imi     sql.NullString
	Itaiji  sql.NullString
	Bushu   sql.NullString
}
